pybo/views/question_views.py
#!/usr/bin/env python
# coding: utf-8

# In[ ]:


#from crypt import methods
#from crypt import methods
from datetime import datetime
from re import search

from flask import Blueprint, render_template, request, url_for, session, g
from werkzeug.utils import redirect, secure_filename

from pybo import db
from pybo.models import Question, User
from ..forms import AnswerForm

from pybo.views.auth_views import login_required

from openpyxl import load_workbook

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list')
@login_required
def _list():
    page = request.args.get('page', type=int, default=1) #페이지
    kw = request.args.get('kw', type=str, default='')


    # ▼▼▼ 정렬 기능은 조금더 공부한 다음에 적용 하자. 전부 주석화
    # 정렬 기능 부분 시작
    # so = request.args.get('so', type=str, default='recent')
    # if so == 'recent':
    #     question_list = Question.query.order_by(Question.date) #출원일 최신 기준
    # elif so == 'recommend':
    #     question_list = Question.query.order_by(Question.p_name)
    # else:
    #     question_list = Question.query.order_by(Question.create_date) #엑셀 데이터 최상단을 위로 하기위해서 .decs()제거
    # 정렬 기능 부분 종료
    # ▲▲▲ 정렬 기능은 조금더 공부한 다음에 적용 하자.

    #question_list=Question.query.order_by(Question.create_date)

    ### ▼▼▼ 사용자별 question_list 구별해서 구현하기 시작

    if g.user:
        question_list=Question.query.order_by(Question.create_date.desc())
        if g.user.username == "관리자":
            #question_list_01 = question_list \
            #    .filter(Question.req_name.ilike('%권다현%')
            #    ) # 의뢰인 자료 기준 검색 req_name)
            #question_list = question_list_01.paginate(page, per_page=10)


            search = '%%{}%%' .format(kw)
            question_list = question_list \
                .filter(Question.p_name.ilike(search) | # 질문 제목 subject => 국문 명칭자료 p_name
                        Question.req_name.ilike(search) | # 의뢰인 자료 기준 검색 req_name
                        Question.our_ref.ilike(search) # 관리번호 기준 검색 our_ref
                        )   


            question_list=question_list.paginate(page, per_page=10)
            return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)
        else:
            name_test_100 = g.user.username # User.username 가 아닌 g.user.username로 했다.
            #User.username 으로 할시 로그아웃 하고 다른 이름으로 로그인할때 기존 User.username가 남아있을수 있어서.
            name_test_101 = "%"+name_test_100+"%"
            question_list_02 = question_list \
                .filter(Question.req_name.ilike(name_test_101))


            search = '%%{}%%' .format(kw)
            question_list_02 = question_list_02 \
                .filter(Question.p_name.ilike(search) | # 질문 제목 subject => 국문 명칭자료 p_name
                        Question.req_name.ilike(search) | # 의뢰인 자료 기준 검색 req_name
                        Question.our_ref.ilike(search) # 관리번호 기준 검색 our_ref
                        )

            question_list = question_list_02.paginate(page, per_page=10)
            return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)
            #pass
    else:
        question_list=Question.query.order_by(Question.create_date)
        #question_list=""


    ### ▲▲▲ 사용자별 question_list 구별해서 구현하기 종료


    #question_list=Question.query.order_by(Question.create_date) #엑셀 데이터 최상단을 위로 하기위해서 .decs()제거
    # 책 예제 기준, 기존 question_list 표현 방식임
    # ㄴ> 정렬기능, 사용자별 리스트 표시 기능 위해서 해당 구문 주석화

    #question_list=Question.query.order_by(Question.create_date.desc())
    # 이하 검색을 위한 기능 구현
    # 기존 예제는 outerjoin 이였지만 우리는 Quesiton 모델 하나만 쓰기에
    # join 형식으로 검색 구현을 해본다.
    if kw:
        search = '%%{}%%' .format(kw)
        question_list = question_list \
            .filter(Question.p_name.ilike(search) | # 질문 제목 subject => 국문 명칭자료 p_name
                    Question.req_name.ilike(search) | # 의뢰인 자료 기준 검색 req_name
                    Question.our_ref.ilike(search) # 관리번호 기준 검색 our_ref
                    )        
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)

@bp.route('/userlist')
@login_required
def userlist():
    user_list = User.query.all()
    return render_template('question/user_list.html', user_list=user_list)


@bp.route('/detail/<int:question_id>/')
@login_required
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)
    
@bp.route('/create/<int:question_id>', methods=("POST",))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)

    if form.validate_on_submit():
        pay_date = request.form['content']
        question.pay_date = pay_date
        #question.create_date = datetime.now()
        #answer=Question(pay_date=pay_date, create_date=datetime.now())
        #question.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/upload_file/')
@login_required
def upload_file():
    return render_template('question/upload_file.html')

@bp.route('/uploader', methods=['GET', 'POST'])
@login_required
def uploader():
    if request.method =='POST':
        f=request.files['file']
        f.save(secure_filename(f.filename))

        # 데이터 입력 부분 시작
        wb = load_workbook(filename='db_test.xlsx')
        ws = wb.active
        test_bb=[]
        test_bb_01=[]


        for row in range(1, ws.max_row+1):
            print_ques=ws.cell(row,1).value

            try:
                test_bb = Question.query.filter(Question.our_ref.ilike(print_ques)).all()
                test_bb_00 = test_bb[0]
                test_bb_01 = test_bb_00.our_ref
            except:
                pass

            if print_ques in test_bb_01:
                test_bb_00.pay_date=ws.cell(row,2).value
                test_bb_00.req_name=ws.cell(row,3).value
                test_bb_00.cus_name=ws.cell(row,4).value
                test_bb_00.date=ws.cell(row,5).value
                test_bb_00.number=ws.cell(row,6).value
                test_bb_00.q_date=ws.cell(row,7).value
                test_bb_00.q_d_date=ws.cell(row,8).value
                test_bb_00.d_d_date=ws.cell(row,9).value
                test_bb_00.d_d_num=ws.cell(row,10).value
                test_bb_00.p_name=ws.cell(row,11).value
                test_bb_00.charge_01=ws.cell(row,12).value
                test_bb_00.charge_02=ws.cell(row,13).value
                test_bb_00.p_charge=ws.cell(row,14).value
                db.session.commit()
            else:
                try:
                    question = Question(our_ref=ws.cell(row,1).value, pay_date=ws.cell(row,2).value, req_name=ws.cell(row,3).value, cus_name=ws.cell(row,4).value, date=ws.cell(row,5).value, number=ws.cell(row,6).value, q_date=ws.cell(row,7).value, q_d_date=ws.cell(row,8).value, d_d_date=ws.cell(row,9).value, d_d_num=ws.cell(row,10).value, p_name=ws.cell(row,11).value, charge_01=ws.cell(row,12).value, charge_02=ws.cell(row,13).value, p_charge=ws.cell(row,14).value, create_date=datetime.now())
                    db.session.add(question)
                    db.session.commit()
                except:
                    db.session.rollback()
                    pass
                finally:
                    db.session.close()
        return redirect(url_for('question._list'))
        #return render_template('question/question_list.html')
        #return '파일이 저장 되었습니다.' + str(Question.query.count())
        #return render_template('question/upload_file.html')
    return render_template('question/question_list.html')
        

pybo/templates/question/question_detail - 복사본 (2)_부트스트랩 적용 이전 백업.html
<h3>{{ question.p_name }}</h3>

<div>
    {{ question.our_ref }}
    
</div>

</br>

<div>
    {{ question.p_charge }}
</div>
</br>

<!-- 입금일 표기부 시작 -->
<h5>입금일자</h5>
<div>
    {{ question.pay_date }}
</div>
<!-- 입금일 표기부 종료 -->
</br>

<h5>입금일자를 등록 해주세요</h5>
<form action="{{ url_for('question.create', question_id=question.id) }}" method="post">
    <textarea name="content" id="content" rows="2"></textarea>
    <input type="submit" value="입금일 등록">
</form>

pybo/templates/question/question_detail - 복사본 (3)_부트스트랩 적용.html
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <h3 class="border-bottom py-2">{{ question.p_name }}</h3>
    

    <!-- 관리번호 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">관리번호</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.our_ref }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 관리번호 표기부 종료 -->

    <!-- 의뢰인 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">의뢰인</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.req_name }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 의뢰인 표기부 종료 -->

    <!-- 출원인 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">출원인</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.cus_name }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 출원인 표기부 종료 -->

    <!-- 출원일 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">출원일 / 출원번호</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.date }} / {{ question.number }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 출원일 표기부 종료 -->

    <!-- 담당자_01 / 담당자_02 / 변리사 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">담당자_01 / 담당자_02 / 변리사</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.charge_01 }} / {{ question.charge_02 }} / {{ question.p_charge }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 담당자_01 / 담당자_02 / 변리사 표기부 종료 -->


    <!-- ======================= -->
    <!-- ======================= -->
    <!-- ======================= -->
    <!-- ======================= -->

    <!-- 입금일 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">입금일자</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.pay_date }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 입금일 표기부 종료 -->

    <!-- 입금일자 입력부 시작-->
    <form action="{{ url_for('question.create', question_id=question.id) }}" method="post" class="my-3">
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="2"></textarea>
        </div>
        <input type="submit" value="입금일 등록" class="btn btn-primary">
    </form>
    <!-- 입금일자 입력부 종료 -->

</div>

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h3>
    <td class="text-start">
        <a href="{{url_for('question._list')}}">{{ question.p_name }}</a>
    </td>
    </h3>

    <!-- 관리번호 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">관리번호</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.our_ref }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 관리번호 표기부 종료 -->

    <!-- 의뢰인 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">의뢰인</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.req_name }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 의뢰인 표기부 종료 -->

    <!-- 출원인 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">출원인</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.cus_name }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 출원인 표기부 종료 -->

    <!-- 출원일 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">출원일 / 출원번호</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.date }} / {{ question.number }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 출원일 표기부 종료 -->

    <!-- 담당자_01 / 담당자_02 / 변리사 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">담당자_01 / 담당자_02 / 변리사</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.charge_01 }} / {{ question.charge_02 }} / {{ question.p_charge }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 담당자_01 / 담당자_02 / 변리사 표기부 종료 -->


    <!-- ======================= -->
    <!-- ======================= -->
    <!-- ======================= -->
    <!-- ======================= -->

    <!-- 입금일 표기부 시작 -->
    <h5 class="border-bottom my-3 py-2">입금일자</h5>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.pay_date }}</div>
            <div class="d-flex justify-content-end">
            </div>
        </div>
    </div>
    <!-- 입금일 표기부 종료 -->

    <!-- 입금일자 입력부 시작-->
    <form action="{{ url_for('question.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ','.join(errors)}}
        </div>
        {% endfor %}
        <!-- 오류표시 end -->


        <!-- 입금일 등록 버튼부 시작-->

        <div class="form-group">
            <textarea {% if not g.user.username == "관리자" %}disabled{% endif %}
            name="content" id="content" class="form-control" rows="2"></textarea>
            <!-- 지정한 계정, 예시에서는 "테스트계정" 이 아니면 disabled 하였다.-->
        </div>
        <input {% if not g.user.username == "관리자" %}disabled{% endif %} type="submit" value="입금일 등록" class="btn btn-primary float-left">
        <!-- 지정한 계정, 예시에서는 "테스트계정" 이 아니면 disabled 하였다.-->

        <!-- 입금일 등록 버튼부 종료-->
        
    </form>
    <!-- 입금일자 입력부 종료 -->

    <!-- 메인페이지 이동부 시작-->
    <form action="{{ url_for('question._list') }}">
        <input type="submit" value="메인페이지 이동" class="btn btn-primary float-right">
    </form>
    <!-- 메인페이지 이동부 종료-->
    

</div>
{% endblock %}

pybo/templates/question/question_list - 복사본 (2).html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 등록하기 예제는 구현하지 않았다. -->

    <!-- 검색기능 구현 시작-->
    <div class="col-6">
        <div class="input-group">
            <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <!-- 검색기능 구현 종료-->

    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>국문명칭</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list.items %}
            <tr>
                <td>{{ question_list.total - ((question_list.page-1)*question_list.per_page)-loop.index0 }}</td>
                <td>
                    <a href="#">{{ question.p_name }}</a>
                </td>
                <td>{{ question.create_date|datetime }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<from id="searchForm" method="get" action="{{ url_for('question._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</from>
{% endblock %}

pybo/templates/question/question_list - 복사본 (3).html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 등록하기 예제는 구현하지 않았다. -->

    <!-- 검색기능 구현 시작-->
    <div class="col-6">
        <div class="input-group">
            <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <!-- 검색기능 구현 종료-->

    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>국문명칭</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list.items %}
            <tr>
                <td>{{ question_list.total - ((question_list.page-1)*question_list.per_page)-loop.index0 }}</td>
                <td>
                    <a href="#">{{ question.p_name }}</a>
                </td>
                <td>{{ question.create_date|datetime }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<from id="searchForm" method="get" action="{{ url_for('question._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</from>
{% endblock %}

<!-- 페이징 및 검색 관련 자바 스크립트 시작-->
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

pybo/templates/question/question_list - 복사본 (4)_번호_의뢰인 등 표현 확장 이전 백업.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <!-- 기능 구현은 아직이다.-->
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so=='recent' %}selected{% endif %}>출원일 최신순</option>
                <option value="recommend" {% if so=='recommend' %}selected{% endif %}>국문 명칭순</option>
                
            </select>
        </div>

        
        <!-- 검색기능 구현 시작-->
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
        <!-- 검색기능 구현 종료-->
    </div>

    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>국문명칭</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list.items %}
            <tr>
                <td>{{ question_list.total - ((question_list.page-1)*question_list.per_page)-loop.index0 }}</td>
                <td>
                    <a href="#">{{ question.p_name }}</a>
                </td>
                <td>{{ question.create_date|datetime }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    
</div>
<form id="searchForm" method="get" action="{{ url_for('question._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
<!-- 검색 스크립트 시작-->
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

pybo/templates/question/question_list - 복사본.html
{% if question_list %}
    <ul>
        {% for question in question_list %}
        <li><a href="#">{{ question.p_name }}</a></li>
        <!-- p_name => 특허내용중 "국문명칭" 내용임 -->
        {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}

pybo/templates/question/upload_file.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">데이터 파일 업로드</h5>
    <form action="http://localhost:5000/question/uploader"
    method="POST" enctype="multipart/form-data">
    <input type="file" name="file" />
    <input type="submit" />
    </form>
</div>
{% endblock %}