pybo/views/auth_views.py
#!/usr/bin/env python
# coding: utf-8

# In[ ]:


#from crypt import methods
from distutils.log import error
import email
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm, UserPassNew
from pybo.models import Question, User

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

@bp.route('/signup/', methods=('GET','POST'))
@login_required
def signup():
    form = UserCreateForm()
    if request.method =='POST' and form.validate_on_submit():
        email = User.query.filter_by(email = form.email.data).first()
        # 기존에는 username=form.username.data 였지만 우리는 email 값으로 비교한다.
        user = User.query.filter_by(username = form.username.data).first()
        if not email and not user:
            email=User(username=form.username.data,
                     password=generate_password_hash(form.password1.data),
                     email=form.email.data)
            db.session.add(email)
            db.session.commit()
            return redirect(url_for('question._list'))
        else:
            if(user):
                flash('이미 존재하는 사용자 입니다.')
            elif(email):
                flash('이미 존재하는 e메일 계정 입니다.')
            else:
                flash('이미 존재하는 사용자, 사용중인 메일 입니다.')
            #flash('이미 존재하는 e메일 계정 입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(email=form.username.data).first()
        # 기존 (username=form.username.data).first() => (email=form.username.data).first() 변경
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error ="비밀번호가 올바르지 않습니다."
        if error is None: # 로그인 id와 비밀번호 맞을때
            session.clear()
            session['user_id'] = user.id # 세션에 키('user_id')와 키값(user.id)저장
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('question._list'))
            #return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.route('/newpass_ss/', methods=('GET', 'POST'))
@login_required
def newpass_ss():
    form = UserPassNew()

    if request.method == 'POST' and form.validate_on_submit():
        password1 = generate_password_hash(form.password1.data)
        g.user.password = password1
        db.session.commit()
        flash('비밀번호를 변경 하였습니다.')



    # 해당 구문 비밀번호 변경 내용 적용하기

    return render_template('auth/new_pass.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

pybo/views/question_views.py
#!/usr/bin/env python
# coding: utf-8

# In[ ]:


#from crypt import methods
#from crypt import methods
from datetime import datetime
from re import search

from flask import Blueprint, render_template, request, url_for, session, g
from werkzeug.utils import redirect, secure_filename

from pybo import db
from pybo.models import Question, User
from ..forms import AnswerForm

from pybo.views.auth_views import login_required

from openpyxl import load_workbook

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list')
@login_required
def _list():
    page = request.args.get('page', type=int, default=1) #페이지
    kw = request.args.get('kw', type=str, default='')


    # ▼▼▼ 정렬 기능은 조금더 공부한 다음에 적용 하자. 전부 주석화
    # 정렬 기능 부분 시작
    # so = request.args.get('so', type=str, default='recent')
    # if so == 'recent':
    #     question_list = Question.query.order_by(Question.date) #출원일 최신 기준
    # elif so == 'recommend':
    #     question_list = Question.query.order_by(Question.p_name)
    # else:
    #     question_list = Question.query.order_by(Question.create_date) #엑셀 데이터 최상단을 위로 하기위해서 .decs()제거
    # 정렬 기능 부분 종료
    # ▲▲▲ 정렬 기능은 조금더 공부한 다음에 적용 하자.

    #question_list=Question.query.order_by(Question.create_date)

    ### ▼▼▼ 사용자별 question_list 구별해서 구현하기 시작

    if g.user:
        question_list=Question.query.order_by(Question.create_date.desc())
        if g.user.username == "관리자":
            #question_list_01 = question_list \
            #    .filter(Question.req_name.ilike('%권다현%')
            #    ) # 의뢰인 자료 기준 검색 req_name)
            #question_list = question_list_01.paginate(page, per_page=10)


            search = '%%{}%%' .format(kw)
            question_list = question_list \
                .filter(Question.p_name.ilike(search) | # 질문 제목 subject => 국문 명칭자료 p_name
                        Question.req_name.ilike(search) | # 의뢰인 자료 기준 검색 req_name
                        Question.our_ref.ilike(search) # 관리번호 기준 검색 our_ref
                        )   


            question_list=question_list.paginate(page, per_page=10)
            return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)
        else:
            name_test_100 = g.user.username # User.username 가 아닌 g.user.username로 했다.
            #User.username 으로 할시 로그아웃 하고 다른 이름으로 로그인할때 기존 User.username가 남아있을수 있어서.
            name_test_101 = "%"+name_test_100+"%"
            question_list_02 = question_list \
                .filter(Question.req_name.ilike(name_test_101))


            search = '%%{}%%' .format(kw)
            question_list_02 = question_list_02 \
                .filter(Question.p_name.ilike(search) | # 질문 제목 subject => 국문 명칭자료 p_name
                        Question.req_name.ilike(search) | # 의뢰인 자료 기준 검색 req_name
                        Question.our_ref.ilike(search) # 관리번호 기준 검색 our_ref
                        )

            question_list = question_list_02.paginate(page, per_page=10)
            return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)
            #pass
    else:
        question_list=Question.query.order_by(Question.create_date)
        #question_list=""


    ### ▲▲▲ 사용자별 question_list 구별해서 구현하기 종료


    #question_list=Question.query.order_by(Question.create_date) #엑셀 데이터 최상단을 위로 하기위해서 .decs()제거
    # 책 예제 기준, 기존 question_list 표현 방식임
    # ㄴ> 정렬기능, 사용자별 리스트 표시 기능 위해서 해당 구문 주석화

    #question_list=Question.query.order_by(Question.create_date.desc())
    # 이하 검색을 위한 기능 구현
    # 기존 예제는 outerjoin 이였지만 우리는 Quesiton 모델 하나만 쓰기에
    # join 형식으로 검색 구현을 해본다.
    if kw:
        search = '%%{}%%' .format(kw)
        question_list = question_list \
            .filter(Question.p_name.ilike(search) | # 질문 제목 subject => 국문 명칭자료 p_name
                    Question.req_name.ilike(search) | # 의뢰인 자료 기준 검색 req_name
                    Question.our_ref.ilike(search) # 관리번호 기준 검색 our_ref
                    )        
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)

@bp.route('/userlist')
@login_required
def userlist():
    user_list = User.query.all()
    return render_template('question/user_list.html', user_list=user_list)


@bp.route('/detail/<int:question_id>/')
@login_required
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)
    
@bp.route('/create/<int:question_id>', methods=("POST",))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)

    if form.validate_on_submit():
        pay_date = request.form['content']
        question.pay_date = pay_date
        #question.create_date = datetime.now()
        #answer=Question(pay_date=pay_date, create_date=datetime.now())
        #question.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/upload_file/')
@login_required
def upload_file():
    return render_template('question/upload_file.html')

@bp.route('/uploader', methods=['GET', 'POST'])
@login_required
def uploader():
    if request.method =='POST':
        f=request.files['file']
        f.save(secure_filename(f.filename))

        # 데이터 입력 부분 시작
        wb = load_workbook(filename='db_test.xlsx')
        ws = wb.active
        test_bb=[]
        test_bb_01=[]


        for row in range(1, ws.max_row+1):
            print_ques=ws.cell(row,1).value

            try:
                test_bb = Question.query.filter(Question.our_ref.ilike(print_ques)).all()
                test_bb_00 = test_bb[0]
                test_bb_01 = test_bb_00.our_ref
            except:
                pass

            if print_ques in test_bb_01:
                test_bb_00.pay_date=ws.cell(row,2).value
                test_bb_00.req_name=ws.cell(row,3).value
                test_bb_00.cus_name=ws.cell(row,4).value
                test_bb_00.date=ws.cell(row,5).value
                test_bb_00.number=ws.cell(row,6).value
                test_bb_00.q_date=ws.cell(row,7).value
                test_bb_00.q_d_date=ws.cell(row,8).value
                test_bb_00.d_d_date=ws.cell(row,9).value
                test_bb_00.d_d_num=ws.cell(row,10).value
                test_bb_00.p_name=ws.cell(row,11).value
                test_bb_00.charge_01=ws.cell(row,12).value
                test_bb_00.charge_02=ws.cell(row,13).value
                test_bb_00.p_charge=ws.cell(row,14).value
                db.session.commit()
            else:
                try:
                    question = Question(our_ref=ws.cell(row,1).value, pay_date=ws.cell(row,2).value, req_name=ws.cell(row,3).value, cus_name=ws.cell(row,4).value, date=ws.cell(row,5).value, number=ws.cell(row,6).value, q_date=ws.cell(row,7).value, q_d_date=ws.cell(row,8).value, d_d_date=ws.cell(row,9).value, d_d_num=ws.cell(row,10).value, p_name=ws.cell(row,11).value, charge_01=ws.cell(row,12).value, charge_02=ws.cell(row,13).value, p_charge=ws.cell(row,14).value, create_date=datetime.now())
                    db.session.add(question)
                    db.session.commit()
                except:
                    db.session.rollback()
                    pass
                finally:
                    db.session.close()
        return redirect(url_for('question._list'))
        #return render_template('question/question_list.html')
        #return '파일이 저장 되었습니다.' + str(Question.query.count())
        #return render_template('question/upload_file.html')
    return render_template('question/question_list.html')
        

pybo/templates/base.html
<html lang="ko">
    <head>
        <!-- required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- bootstrap css -->
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
        <!-- pybo css -->
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <title>특허관리 시스템</title>
    </head>
    <body>
        <!-- 네비게이션바 입력 시작 -->
        {% include "navbar.html" %}
        <!-- 네비게이션바 입력 종료 -->

        <!-- 기본 템플릿 안에 삽입될 내용 start -->
        {% block content %}
        {% endblock %}
        <!-- 제이쿼리.js -->
        <script src="{{url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
        <!-- 부트스트랩.js -->
        <script src="{{url_for('static', filename='bootstrap.min.js') }}"></script>
        <!-- 기본 템플릿 안에 삽입될 내용 end -->

        <!-- 자바스크립트 시작-->
        {% block script %}
        {% endblock %}
        <!-- 자바스크립트 종료-->
    </body>

</html>

pybo/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pybo/templates/navbar.html
        <!-- 네비게이션바 입력 시작 -->
        <nav class="navbar navbar-expand-lg navbar-light bf-light border-bottom">
            {% if g.user %}
            <a class="navbar-brand" href="{{ url_for('question._list') }}">특허관리 시스템</a>
            {% else %}
            <a class="navbar-brand" href="#">특허관리 시스템</a>
            {% endif %}
            <!-- 해당 글자 클릭하면 url_for 통해서 main.index 로 이동됨 -->

            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle naviagtion">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
                {% if g.user %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">'{{ g.user.username }}' 님 방문을 환영합니다. (로그아웃)</a>
                        <!-- {{ g.user.username }} 의 username 부분을 email 등으로 바꿔도 된다. -->
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.newpass_ss')}}">비밀번호 변경
                            <!-- 링크 적용 테스트 단계 -->
                        </a>
                    </li>

                    
                    {% if g.user.username == "관리자" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('question.userlist') }}">회원관리</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('question.upload_file') }}">데이터 업로드</a>
                    </li>
                    {% endif %}

                    

                </ul>
                {% else %}
                <ul class="navbar-nav">
                    

                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
        <!-- 네비게이션바 입력 종료 -->